title: Target practice
hero_image: images/banner.png
description: Use Python to draw a target and score points by hitting it with arrows
meta_title: Python coding projects for kids and teens | Target practice
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Use Python to draw a target and score points by hitting it with arrows.
version: 4
listed: false
copyedit: false
last_tested: "2021-10-06"
steps:
  - title: You will make
  - title: Create a background
  - title: Draw the grass
  - title: Draw your target
    completion:
      - engaged
  - title: Fire your arrow
  - title: Get the colour hit by the arrow
  - title: Score points
    completion:
      - internal
  - title: Add more conditions
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project
  - title: What next?
